<?php

return [
    'channels' => [
        'references' => [
            'key' => 'references',
            'label' => 'Referensi Neo Feeder',
            'description' => 'Lookup master dari Neo Feeder untuk validasi template dan mapping data.',
            'depends_on' => [],
            'sort_order' => 10,
            'fields' => [
                [
                    'name' => 'endpoint',
                    'label' => 'Endpoint',
                    'type' => 'string',
                    'required' => true,
                    'nullable' => false,
                    'description' => 'Nama aksi Get* Neo Feeder.',
                ],
                [
                    'name' => 'value',
                    'label' => 'Value',
                    'type' => 'string',
                    'required' => true,
                    'nullable' => false,
                    'description' => 'ID atau kode referensi yang dipakai pada payload.',
                ],
                [
                    'name' => 'label',
                    'label' => 'Label',
                    'type' => 'string',
                    'required' => true,
                    'nullable' => false,
                    'description' => 'Nama referensi yang tampil di UI/template.',
                ],
                [
                    'name' => 'raw',
                    'label' => 'Raw Data',
                    'type' => 'json',
                    'required' => false,
                    'nullable' => true,
                    'description' => 'Response mentah per record dari Neo Feeder.',
                ],
            ],
            'operations' => [
                [
                    'name' => 'profil_pt',
                    'action' => 'GetProfilPT',
                    'type' => 'read',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_perguruan_tinggi', 'kode_perguruan_tinggi', 'nama_perguruan_tinggi'],
                ],
                [
                    'name' => 'prodi',
                    'action' => 'GetProdi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_prodi', 'kode_program_studi', 'nama_program_studi'],
                ],
                [
                    'name' => 'semester',
                    'action' => 'GetSemester',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_semester', 'nama_semester'],
                ],
                [
                    'name' => 'agama',
                    'action' => 'GetAgama',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_agama', 'nama_agama'],
                ],
                [
                    'name' => 'negara',
                    'action' => 'GetNegara',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_negara', 'nama_negara'],
                ],
                [
                    'name' => 'wilayah',
                    'action' => 'GetWilayah',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_wilayah', 'nama_wilayah'],
                ],
                [
                    'name' => 'jenis_tinggal',
                    'action' => 'GetJenisTinggal',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_tinggal', 'nama_jenis_tinggal'],
                ],
                [
                    'name' => 'alat_transportasi',
                    'action' => 'GetAlatTransportasi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_alat_transportasi', 'nama_alat_transportasi'],
                ],
                [
                    'name' => 'jenis_pendaftaran',
                    'action' => 'GetJenisPendaftaran',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_daftar', 'nama_jenis_daftar'],
                ],
                [
                    'name' => 'jalur_masuk',
                    'action' => 'GetJalurMasuk',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jalur_masuk', 'nama_jalur_masuk'],
                ],
                [
                    'name' => 'pembiayaan',
                    'action' => 'GetPembiayaan',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_pembiayaan', 'nama_pembiayaan'],
                ],
                [
                    'name' => 'status_mahasiswa',
                    'action' => 'GetStatusMahasiswa',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_status_mahasiswa', 'nama_status_mahasiswa'],
                ],
                [
                    'name' => 'jenis_keluar',
                    'action' => 'GetJenisKeluar',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_keluar', 'nama_jenis_keluar'],
                ],
                [
                    'name' => 'jenis_evaluasi',
                    'action' => 'GetJenisEvaluasi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_evaluasi', 'nama_jenis_evaluasi'],
                ],
                [
                    'name' => 'kategori_kegiatan',
                    'action' => 'GetKategoriKegiatan',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_kategori_kegiatan', 'nama_kategori_kegiatan'],
                ],
                [
                    'name' => 'basis_evaluasi',
                    'action' => 'GetBasisEvaluasi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_basis_evaluasi', 'nama_basis_evaluasi'],
                ],
                [
                    'name' => 'dosen',
                    'action' => 'GetListDosen',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_dosen', 'nidn', 'nama_dosen'],
                ],
            ],
        ],
        'mahasiswa_biodata' => [
            'key' => 'mahasiswa_biodata',
            'label' => 'Biodata Mahasiswa',
            'description' => 'Biodata pokok mahasiswa untuk InsertBiodataMahasiswa dan identitas awal sebelum riwayat pendidikan.',
            'sheet_name' => 'mahasiswa_biodata',
            'depends_on' => ['references'],
            'natural_key' => ['nik'],
            'identity_fields' => ['id_mahasiswa'],
            'sort_order' => 100,
            'fields' => [
                ['name' => 'id_mahasiswa', 'label' => 'ID Mahasiswa', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete. Kosong saat insert baru.'],
                ['name' => 'nama_mahasiswa', 'label' => 'Nama Mahasiswa', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 100],
                ['name' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 1, 'rules' => ['enum:L,P,*']],
                ['name' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 32],
                ['name' => 'tanggal_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'nullable' => false, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_agama', 'label' => 'Agama', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetAgama'],
                ['name' => 'nik', 'label' => 'NIK', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 16, 'rules' => ['digits:16']],
                ['name' => 'nisn', 'label' => 'NISN', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 10],
                ['name' => 'npwp', 'label' => 'NPWP', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 15],
                ['name' => 'kewarganegaraan', 'label' => 'Kewarganegaraan', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 2, 'reference' => 'GetNegara'],
                ['name' => 'jalan', 'label' => 'Jalan', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 80],
                ['name' => 'dusun', 'label' => 'Dusun', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 60],
                ['name' => 'rt', 'label' => 'RT', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2],
                ['name' => 'rw', 'label' => 'RW', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2],
                ['name' => 'kelurahan', 'label' => 'Kelurahan', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 60],
                ['name' => 'kode_pos', 'label' => 'Kode Pos', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 5],
                ['name' => 'id_wilayah', 'label' => 'Wilayah', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 8, 'reference' => 'GetWilayah'],
                ['name' => 'id_jenis_tinggal', 'label' => 'Jenis Tinggal', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenisTinggal'],
                ['name' => 'id_alat_transportasi', 'label' => 'Alat Transportasi', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetAlatTransportasi'],
                ['name' => 'telepon', 'label' => 'Telepon', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 20],
                ['name' => 'handphone', 'label' => 'Handphone', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 20],
                ['name' => 'email', 'label' => 'Email', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 60, 'rules' => ['email_warning']],
                ['name' => 'penerima_kps', 'label' => 'Penerima KPS', 'type' => 'boolean01', 'required' => true, 'nullable' => false, 'rules' => ['enum:0,1']],
                ['name' => 'nomor_kps', 'label' => 'Nomor KPS', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 80, 'rules' => ['required_warning_if:penerima_kps,1']],
                ['name' => 'nik_ayah', 'label' => 'NIK Ayah', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 16, 'rules' => ['digits_if_filled:16']],
                ['name' => 'nama_ayah', 'label' => 'Nama Ayah', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 100],
                ['name' => 'tanggal_lahir_ayah', 'label' => 'Tanggal Lahir Ayah', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_pendidikan_ayah', 'label' => 'Pendidikan Ayah', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenjangPendidikan'],
                ['name' => 'id_pekerjaan_ayah', 'label' => 'Pekerjaan Ayah', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPekerjaan'],
                ['name' => 'id_penghasilan_ayah', 'label' => 'Penghasilan Ayah', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPenghasilan'],
                ['name' => 'nik_ibu', 'label' => 'NIK Ibu', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 16, 'rules' => ['digits_if_filled:16']],
                ['name' => 'nama_ibu_kandung', 'label' => 'Nama Ibu Kandung', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 100],
                ['name' => 'tanggal_lahir_ibu', 'label' => 'Tanggal Lahir Ibu', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_pendidikan_ibu', 'label' => 'Pendidikan Ibu', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenjangPendidikan'],
                ['name' => 'id_pekerjaan_ibu', 'label' => 'Pekerjaan Ibu', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPekerjaan'],
                ['name' => 'id_penghasilan_ibu', 'label' => 'Penghasilan Ibu', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPenghasilan'],
                ['name' => 'nama_wali', 'label' => 'Nama Wali', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 100],
                ['name' => 'tanggal_lahir_wali', 'label' => 'Tanggal Lahir Wali', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_pendidikan_wali', 'label' => 'Pendidikan Wali', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenjangPendidikan'],
                ['name' => 'id_pekerjaan_wali', 'label' => 'Pekerjaan Wali', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPekerjaan'],
                ['name' => 'id_penghasilan_wali', 'label' => 'Penghasilan Wali', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPenghasilan'],
                ['name' => 'id_kebutuhan_khusus_mahasiswa', 'label' => 'Kebutuhan Khusus Mahasiswa', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetKebutuhanKhusus', 'example' => 0],
                ['name' => 'id_kebutuhan_khusus_ayah', 'label' => 'Kebutuhan Khusus Ayah', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetKebutuhanKhusus', 'example' => 0],
                ['name' => 'id_kebutuhan_khusus_ibu', 'label' => 'Kebutuhan Khusus Ibu', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetKebutuhanKhusus', 'example' => 0],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetBiodataMahasiswa', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_mahasiswa']],
                ['name' => 'insert', 'action' => 'InsertBiodataMahasiswa', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_mahasiswa']],
                ['name' => 'update', 'action' => 'UpdateBiodataMahasiswa', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_mahasiswa']],
                ['name' => 'delete', 'action' => 'DeleteBiodataMahasiswa', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_mahasiswa']],
            ],
        ],
        'mahasiswa_riwayat_pendidikan' => [
            'key' => 'mahasiswa_riwayat_pendidikan',
            'label' => 'Riwayat Pendidikan Mahasiswa',
            'description' => 'Registrasi mahasiswa pada program studi/periode masuk setelah biodata mahasiswa tersimpan.',
            'sheet_name' => 'mahasiswa_riwayat_pendidikan',
            'depends_on' => ['references', 'mahasiswa_biodata'],
            'natural_key' => ['nim', 'id_prodi', 'id_periode_masuk'],
            'identity_fields' => ['id_registrasi_mahasiswa'],
            'sort_order' => 110,
            'fields' => [
                ['name' => 'id_registrasi_mahasiswa', 'label' => 'ID Registrasi Mahasiswa', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete riwayat pendidikan. Kosong saat insert baru.'],
                ['name' => 'id_mahasiswa', 'label' => 'ID Mahasiswa', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'mahasiswa_biodata.id_mahasiswa'],
                ['name' => 'nim', 'label' => 'NIM', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 24],
                ['name' => 'id_jenis_daftar', 'label' => 'Jenis Pendaftaran', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'max_length' => 2, 'reference' => 'GetJenisPendaftaran'],
                ['name' => 'id_jalur_daftar', 'label' => 'Jalur Masuk', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 4, 'reference' => 'GetJalurMasuk'],
                ['name' => 'id_periode_masuk', 'label' => 'Periode Masuk', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 5, 'reference' => 'GetSemester'],
                ['name' => 'tanggal_daftar', 'label' => 'Tanggal Daftar', 'type' => 'date', 'required' => true, 'nullable' => false, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_perguruan_tinggi', 'label' => 'Perguruan Tinggi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProfilPT'],
                ['name' => 'id_prodi', 'label' => 'Program Studi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProdi'],
                ['name' => 'id_bidang_minat', 'label' => 'Bidang Minat', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetListBidangMinat'],
                ['name' => 'sks_diakui', 'label' => 'SKS Diakui', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 3],
                ['name' => 'id_perguruan_tinggi_asal', 'label' => 'Perguruan Tinggi Asal', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetAllPT'],
                ['name' => 'id_prodi_asal', 'label' => 'Program Studi Asal', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetAllProdi'],
                ['name' => 'id_pembiayaan', 'label' => 'Pembiayaan', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'reference' => 'GetPembiayaan'],
                ['name' => 'biaya_masuk', 'label' => 'Biaya Masuk', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:16,2']],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetListRiwayatPendidikanMahasiswa', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'insert', 'action' => 'InsertRiwayatPendidikanMahasiswa', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'update', 'action' => 'UpdateRiwayatPendidikanMahasiswa', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'delete', 'action' => 'DeleteRiwayatPendidikanMahasiswa', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_registrasi_mahasiswa']],
            ],
        ],
        'mata_kuliah' => [
            'key' => 'mata_kuliah',
            'label' => 'Mata Kuliah',
            'description' => 'Master mata kuliah per program studi untuk kelas kuliah, kurikulum, peserta, dan nilai.',
            'sheet_name' => 'mata_kuliah',
            'depends_on' => ['references'],
            'natural_key' => ['id_prodi', 'kode_mata_kuliah'],
            'identity_fields' => ['id_matkul'],
            'sort_order' => 200,
            'fields' => [
                ['name' => 'id_matkul', 'label' => 'ID Mata Kuliah', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete. Kosong saat insert baru.'],
                ['name' => 'kode_mata_kuliah', 'label' => 'Kode Mata Kuliah', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 20],
                ['name' => 'nama_mata_kuliah', 'label' => 'Nama Mata Kuliah', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 200],
                ['name' => 'id_prodi', 'label' => 'Program Studi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProdi'],
                ['name' => 'id_jenis_mata_kuliah', 'label' => 'Jenis Mata Kuliah', 'type' => 'char', 'required' => false, 'nullable' => true, 'max_length' => 1, 'rules' => ['enum:A,B,C,D,S']],
                ['name' => 'id_kelompok_mata_kuliah', 'label' => 'Kelompok Mata Kuliah', 'type' => 'char', 'required' => false, 'nullable' => true, 'max_length' => 1, 'rules' => ['enum:A,B,C,D,E,F,G,H']],
                ['name' => 'sks_mata_kuliah', 'label' => 'SKS Mata Kuliah', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:5,2', 'min:1']],
                ['name' => 'sks_tatap_muka', 'label' => 'SKS Tatap Muka', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_praktek', 'label' => 'SKS Praktik', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_praktek_lapangan', 'label' => 'SKS Praktik Lapangan', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_simulasi', 'label' => 'SKS Simulasi', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'metode_kuliah', 'label' => 'Metode Kuliah', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 50],
                ['name' => 'ada_sap', 'label' => 'Ada SAP', 'type' => 'boolean01', 'required' => false, 'nullable' => true, 'rules' => ['enum:0,1']],
                ['name' => 'ada_silabus', 'label' => 'Ada Silabus', 'type' => 'boolean01', 'required' => false, 'nullable' => true, 'rules' => ['enum:0,1']],
                ['name' => 'ada_bahan_ajar', 'label' => 'Ada Bahan Ajar', 'type' => 'boolean01', 'required' => false, 'nullable' => true, 'rules' => ['enum:0,1']],
                ['name' => 'ada_acara_praktek', 'label' => 'Ada Acara Praktik', 'type' => 'boolean01', 'required' => false, 'nullable' => true, 'rules' => ['enum:0,1']],
                ['name' => 'ada_diktat', 'label' => 'Ada Diktat', 'type' => 'boolean01', 'required' => false, 'nullable' => true, 'rules' => ['enum:0,1']],
                ['name' => 'tanggal_mulai_efektif', 'label' => 'Tanggal Mulai Efektif', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'tanggal_akhir_efektif', 'label' => 'Tanggal Akhir Efektif', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetListMataKuliah', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_matkul']],
                ['name' => 'insert', 'action' => 'InsertMataKuliah', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_matkul']],
                ['name' => 'update', 'action' => 'UpdateMataKuliah', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_matkul']],
                ['name' => 'delete', 'action' => 'DeleteMataKuliah', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_matkul']],
            ],
        ],
        'kurikulum' => [
            'key' => 'kurikulum',
            'label' => 'Kurikulum',
            'description' => 'Kurikulum per program studi dan periode semester untuk relasi mata kuliah kurikulum.',
            'sheet_name' => 'kurikulum',
            'depends_on' => ['references'],
            'natural_key' => ['id_prodi', 'id_semester', 'nama_kurikulum'],
            'identity_fields' => ['id_kurikulum'],
            'sort_order' => 210,
            'fields' => [
                ['name' => 'id_kurikulum', 'label' => 'ID Kurikulum', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete. Kosong saat insert baru.'],
                ['name' => 'nama_kurikulum', 'label' => 'Nama Kurikulum', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 60],
                ['name' => 'id_prodi', 'label' => 'Program Studi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProdi'],
                ['name' => 'id_semester', 'label' => 'Semester', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 5, 'reference' => 'GetSemester'],
                ['name' => 'jumlah_sks_lulus', 'label' => 'Jumlah SKS Lulus', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'max_length' => 3],
                ['name' => 'jumlah_sks_wajib', 'label' => 'Jumlah SKS Wajib', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'max_length' => 3],
                ['name' => 'jumlah_sks_pilihan', 'label' => 'Jumlah SKS Pilihan', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'max_length' => 3],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetListKurikulum', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_kurikulum']],
                ['name' => 'insert', 'action' => 'InsertKurikulum', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_kurikulum']],
                ['name' => 'update', 'action' => 'UpdateKurikulum', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_kurikulum']],
                ['name' => 'delete', 'action' => 'DeleteKurikulum', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_kurikulum']],
            ],
        ],
        'matkul_kurikulum' => [
            'key' => 'matkul_kurikulum',
            'label' => 'Mata Kuliah Kurikulum',
            'description' => 'Relasi mata kuliah ke kurikulum beserta semester penempatan dan bobot SKS.',
            'sheet_name' => 'matkul_kurikulum',
            'depends_on' => ['kurikulum', 'mata_kuliah'],
            'natural_key' => ['id_kurikulum', 'id_matkul'],
            'identity_fields' => [],
            'sort_order' => 220,
            'fields' => [
                ['name' => 'id_kurikulum', 'label' => 'Kurikulum', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListKurikulum'],
                ['name' => 'id_matkul', 'label' => 'Mata Kuliah', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListMataKuliah'],
                ['name' => 'semester', 'label' => 'Semester Penempatan', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:2,0', 'min:1', 'max:14']],
                ['name' => 'sks_mata_kuliah', 'label' => 'SKS Mata Kuliah', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_tatap_muka', 'label' => 'SKS Tatap Muka', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_praktek', 'label' => 'SKS Praktik', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_praktek_lapangan', 'label' => 'SKS Praktik Lapangan', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'sks_simulasi', 'label' => 'SKS Simulasi', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,2']],
                ['name' => 'apakah_wajib', 'label' => 'Wajib', 'type' => 'boolean01', 'required' => true, 'nullable' => false, 'rules' => ['enum:0,1']],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetMatkulKurikulum', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_kurikulum', 'id_matkul']],
                ['name' => 'insert', 'action' => 'InsertMatkulKurikulum', 'type' => 'insert', 'payload_mode' => 'record'],
                ['name' => 'delete', 'action' => 'DeleteMatkulKurikulum', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_kurikulum', 'id_matkul']],
            ],
        ],
        'kelas_kuliah' => [
            'key' => 'kelas_kuliah',
            'label' => 'Kelas Kuliah',
            'description' => 'Kelas perkuliahan per semester, program studi, dan mata kuliah.',
            'sheet_name' => 'kelas_kuliah',
            'depends_on' => ['mata_kuliah', 'references'],
            'natural_key' => ['id_semester', 'id_prodi', 'id_matkul', 'nama_kelas_kuliah'],
            'identity_fields' => ['id_kelas_kuliah'],
            'sort_order' => 300,
            'fields' => [
                ['name' => 'id_kelas_kuliah', 'label' => 'ID Kelas Kuliah', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete. Kosong saat insert baru.'],
                ['name' => 'id_prodi', 'label' => 'Program Studi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProdi'],
                ['name' => 'id_semester', 'label' => 'Semester', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 5, 'reference' => 'GetSemester'],
                ['name' => 'id_matkul', 'label' => 'Mata Kuliah', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListMataKuliah'],
                ['name' => 'nama_kelas_kuliah', 'label' => 'Nama Kelas Kuliah', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 5],
                ['name' => 'bahasan', 'label' => 'Bahasan', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 200],
                ['name' => 'tanggal_mulai_efektif', 'label' => 'Tanggal Mulai Efektif', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'tanggal_akhir_efektif', 'label' => 'Tanggal Akhir Efektif', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'tanggal_tutup_daftar', 'label' => 'Tanggal Tutup Daftar', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'apa_untuk_pditt', 'label' => 'Untuk PDITT', 'type' => 'boolean01', 'required' => true, 'nullable' => false, 'rules' => ['enum:0,1']],
                ['name' => 'kapasitas', 'label' => 'Kapasitas', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:5,0']],
                ['name' => 'lingkup', 'label' => 'Lingkup', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:1,0', 'enum:1,2,3']],
                ['name' => 'mode', 'label' => 'Mode', 'type' => 'char', 'required' => false, 'nullable' => true, 'max_length' => 1, 'rules' => ['enum:O,F,M']],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetListKelasKuliah', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_kelas_kuliah']],
                ['name' => 'insert', 'action' => 'InsertKelasKuliah', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_kelas_kuliah']],
                ['name' => 'update', 'action' => 'UpdateKelasKuliah', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_kelas_kuliah']],
                ['name' => 'delete', 'action' => 'DeleteKelasKuliah', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_kelas_kuliah']],
            ],
        ],
        'peserta_kelas' => [
            'key' => 'peserta_kelas',
            'label' => 'Peserta Kelas Kuliah',
            'description' => 'Relasi mahasiswa terdaftar ke kelas kuliah.',
            'sheet_name' => 'peserta_kelas',
            'depends_on' => ['kelas_kuliah', 'mahasiswa_riwayat_pendidikan'],
            'natural_key' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa'],
            'identity_fields' => [],
            'sort_order' => 310,
            'fields' => [
                ['name' => 'id_kelas_kuliah', 'label' => 'Kelas Kuliah', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListKelasKuliah'],
                ['name' => 'id_registrasi_mahasiswa', 'label' => 'Registrasi Mahasiswa', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListRiwayatPendidikanMahasiswa'],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetPesertaKelasKuliah', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa']],
                ['name' => 'insert', 'action' => 'InsertPesertaKelasKuliah', 'type' => 'insert', 'payload_mode' => 'record'],
                ['name' => 'delete', 'action' => 'DeletePesertaKelasKuliah', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa']],
            ],
        ],
        'dosen_pengajar_kelas' => [
            'key' => 'dosen_pengajar_kelas',
            'label' => 'Dosen Pengajar Kelas Kuliah',
            'description' => 'Aktivitas mengajar dosen pada kelas kuliah.',
            'sheet_name' => 'dosen_pengajar_kelas',
            'depends_on' => ['kelas_kuliah', 'references'],
            'natural_key' => ['id_kelas_kuliah', 'id_registrasi_dosen', 'id_substansi'],
            'identity_fields' => ['id_aktivitas_mengajar'],
            'sort_order' => 320,
            'fields' => [
                ['name' => 'id_aktivitas_mengajar', 'label' => 'ID Aktivitas Mengajar', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete. Kosong saat insert baru.'],
                ['name' => 'id_registrasi_dosen', 'label' => 'Registrasi Dosen', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListPenugasanDosen'],
                ['name' => 'id_kelas_kuliah', 'label' => 'Kelas Kuliah', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListKelasKuliah'],
                ['name' => 'id_substansi', 'label' => 'Substansi Kuliah', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetListSubstansiKuliah'],
                ['name' => 'sks_substansi_total', 'label' => 'SKS Substansi Total', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:5,2']],
                ['name' => 'rencana_minggu_pertemuan', 'label' => 'Rencana Minggu Pertemuan', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:2,0']],
                ['name' => 'realisasi_minggu_pertemuan', 'label' => 'Realisasi Minggu Pertemuan', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:2,0']],
                ['name' => 'id_jenis_evaluasi', 'label' => 'Jenis Evaluasi', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetJenisEvaluasi'],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetDosenPengajarKelasKuliah', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_aktivitas_mengajar']],
                ['name' => 'insert', 'action' => 'InsertDosenPengajarKelasKuliah', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_aktivitas_mengajar']],
                ['name' => 'update', 'action' => 'UpdateDosenPengajarKelasKuliah', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_aktivitas_mengajar']],
                ['name' => 'delete', 'action' => 'DeleteDosenPengajarKelasKuliah', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_aktivitas_mengajar']],
            ],
        ],
        'nilai_perkuliahan' => [
            'key' => 'nilai_perkuliahan',
            'label' => 'Nilai Perkuliahan Kelas',
            'description' => 'Nilai angka, indeks, dan huruf untuk peserta kelas kuliah.',
            'sheet_name' => 'nilai_perkuliahan',
            'depends_on' => ['peserta_kelas'],
            'natural_key' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa'],
            'identity_fields' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa'],
            'sort_order' => 330,
            'fields' => [
                ['name' => 'id_registrasi_mahasiswa', 'label' => 'Registrasi Mahasiswa', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListRiwayatPendidikanMahasiswa'],
                ['name' => 'id_kelas_kuliah', 'label' => 'Kelas Kuliah', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListKelasKuliah'],
                ['name' => 'nilai_angka', 'label' => 'Nilai Angka', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:4,1', 'min:0', 'max:100']],
                ['name' => 'nilai_indeks', 'label' => 'Nilai Indeks', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:4,2', 'min:0', 'max:4']],
                ['name' => 'nilai_huruf', 'label' => 'Nilai Huruf', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 3],
            ],
            'operations' => [
                ['name' => 'get_list', 'action' => 'GetListNilaiPerkuliahanKelas', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_kelas_kuliah']],
                ['name' => 'get_detail', 'action' => 'GetDetailNilaiPerkuliahanKelas', 'type' => 'read', 'payload_mode' => 'filter', 'key_fields' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa']],
                ['name' => 'update', 'action' => 'UpdateNilaiPerkuliahanKelas', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_kelas_kuliah', 'id_registrasi_mahasiswa']],
            ],
        ],
        'perkuliahan_mahasiswa_akm' => [
            'key' => 'perkuliahan_mahasiswa_akm',
            'label' => 'AKM Perkuliahan Mahasiswa',
            'description' => 'Aktivitas kuliah mahasiswa per semester, termasuk status, IPS/IPK, SKS, dan biaya kuliah semester.',
            'sheet_name' => 'perkuliahan_mahasiswa_akm',
            'depends_on' => ['mahasiswa_riwayat_pendidikan', 'references'],
            'natural_key' => ['id_registrasi_mahasiswa', 'id_semester'],
            'identity_fields' => ['id_registrasi_mahasiswa', 'id_semester'],
            'sort_order' => 340,
            'fields' => [
                ['name' => 'id_registrasi_mahasiswa', 'label' => 'Registrasi Mahasiswa', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListRiwayatPendidikanMahasiswa'],
                ['name' => 'id_semester', 'label' => 'Semester', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 5, 'reference' => 'GetSemester'],
                ['name' => 'id_status_mahasiswa', 'label' => 'Status Mahasiswa', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 1, 'reference' => 'GetStatusMahasiswa'],
                ['name' => 'ips', 'label' => 'IPS', 'type' => 'double', 'required' => false, 'nullable' => true, 'rules' => ['min:0', 'max:4']],
                ['name' => 'ipk', 'label' => 'IPK', 'type' => 'double', 'required' => false, 'nullable' => true, 'rules' => ['min:0', 'max:4']],
                ['name' => 'sks_semester', 'label' => 'SKS Semester', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:3,0']],
                ['name' => 'total_sks', 'label' => 'Total SKS', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:3,0']],
                ['name' => 'biaya_kuliah_smt', 'label' => 'Biaya Kuliah Semester', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:16,2']],
            ],
            'operations' => [
                ['name' => 'get_list', 'action' => 'GetListPerkuliahanMahasiswa', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_registrasi_mahasiswa', 'id_semester']],
                ['name' => 'get_detail', 'action' => 'GetDetailPerkuliahanMahasiswa', 'type' => 'read', 'payload_mode' => 'filter', 'key_fields' => ['id_registrasi_mahasiswa', 'id_semester']],
                ['name' => 'insert', 'action' => 'InsertPerkuliahanMahasiswa', 'type' => 'insert', 'payload_mode' => 'record'],
                ['name' => 'update', 'action' => 'UpdatePerkuliahanMahasiswa', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_registrasi_mahasiswa', 'id_semester']],
                ['name' => 'delete', 'action' => 'DeletePerkuliahanMahasiswa', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_registrasi_mahasiswa', 'id_semester']],
            ],
        ],
        'mahasiswa_lulus_do' => [
            'key' => 'mahasiswa_lulus_do',
            'label' => 'Mahasiswa Lulus/DO',
            'description' => 'Data keluar mahasiswa, termasuk lulus, drop out, mutasi, dan status keluar lain.',
            'sheet_name' => 'mahasiswa_lulus_do',
            'depends_on' => ['mahasiswa_riwayat_pendidikan', 'references'],
            'natural_key' => ['id_registrasi_mahasiswa'],
            'identity_fields' => ['id_registrasi_mahasiswa'],
            'sort_order' => 350,
            'fields' => [
                ['name' => 'id_registrasi_mahasiswa', 'label' => 'Registrasi Mahasiswa', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetListRiwayatPendidikanMahasiswa'],
                ['name' => 'id_jenis_keluar', 'label' => 'Jenis Keluar', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 1, 'reference' => 'GetJenisKeluar'],
                ['name' => 'tanggal_keluar', 'label' => 'Tanggal Keluar', 'type' => 'date', 'required' => true, 'nullable' => false, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_periode_keluar', 'label' => 'Periode Keluar', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:5,0'], 'reference' => 'GetListPeriodePerkuliahan'],
                ['name' => 'keterangan', 'label' => 'Keterangan', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 128],
                ['name' => 'nomor_sk_yudisium', 'label' => 'Nomor SK Yudisium', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 80],
                ['name' => 'tanggal_sk_yudisium', 'label' => 'Tanggal SK Yudisium', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'ipk', 'label' => 'IPK', 'type' => 'double', 'required' => false, 'nullable' => true, 'rules' => ['min:0', 'max:4']],
                ['name' => 'nomor_ijazah', 'label' => 'Nomor Ijazah', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 80],
                ['name' => 'jalur_skripsi', 'label' => 'Jalur Skripsi', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'rules' => ['decimal:1,0']],
                ['name' => 'judul_skripsi', 'label' => 'Judul Skripsi', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 500],
                ['name' => 'bulan_awal_bimbingan', 'label' => 'Bulan Awal Bimbingan', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'bulan_akhir_bimbingan', 'label' => 'Bulan Akhir Bimbingan', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
            ],
            'operations' => [
                ['name' => 'get_list', 'action' => 'GetListMahasiswaLulusDO', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'get_detail', 'action' => 'GetDetailMahasiswaLulusDO', 'type' => 'read', 'payload_mode' => 'filter', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'insert', 'action' => 'InsertMahasiswaLulusDO', 'type' => 'insert', 'payload_mode' => 'record'],
                ['name' => 'update', 'action' => 'UpdateMahasiswaLulusDO', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'delete', 'action' => 'DeleteMahasiswaLulusDO', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_registrasi_mahasiswa']],
            ],
        ],
    ],
];
