<?php

return [
    'channels' => [
        'references' => [
            'key' => 'references',
            'label' => 'Referensi Neo Feeder',
            'description' => 'Lookup master dari Neo Feeder untuk validasi template dan mapping data.',
            'depends_on' => [],
            'sort_order' => 10,
            'fields' => [
                [
                    'name' => 'endpoint',
                    'label' => 'Endpoint',
                    'type' => 'string',
                    'required' => true,
                    'nullable' => false,
                    'description' => 'Nama aksi Get* Neo Feeder.',
                ],
                [
                    'name' => 'value',
                    'label' => 'Value',
                    'type' => 'string',
                    'required' => true,
                    'nullable' => false,
                    'description' => 'ID atau kode referensi yang dipakai pada payload.',
                ],
                [
                    'name' => 'label',
                    'label' => 'Label',
                    'type' => 'string',
                    'required' => true,
                    'nullable' => false,
                    'description' => 'Nama referensi yang tampil di UI/template.',
                ],
                [
                    'name' => 'raw',
                    'label' => 'Raw Data',
                    'type' => 'json',
                    'required' => false,
                    'nullable' => true,
                    'description' => 'Response mentah per record dari Neo Feeder.',
                ],
            ],
            'operations' => [
                [
                    'name' => 'profil_pt',
                    'action' => 'GetProfilPT',
                    'type' => 'read',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_perguruan_tinggi', 'kode_perguruan_tinggi', 'nama_perguruan_tinggi'],
                ],
                [
                    'name' => 'prodi',
                    'action' => 'GetProdi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_prodi', 'kode_program_studi', 'nama_program_studi'],
                ],
                [
                    'name' => 'semester',
                    'action' => 'GetSemester',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_semester', 'nama_semester'],
                ],
                [
                    'name' => 'agama',
                    'action' => 'GetAgama',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_agama', 'nama_agama'],
                ],
                [
                    'name' => 'negara',
                    'action' => 'GetNegara',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_negara', 'nama_negara'],
                ],
                [
                    'name' => 'wilayah',
                    'action' => 'GetWilayah',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_wilayah', 'nama_wilayah'],
                ],
                [
                    'name' => 'jenis_tinggal',
                    'action' => 'GetJenisTinggal',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_tinggal', 'nama_jenis_tinggal'],
                ],
                [
                    'name' => 'alat_transportasi',
                    'action' => 'GetAlatTransportasi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_alat_transportasi', 'nama_alat_transportasi'],
                ],
                [
                    'name' => 'jenis_pendaftaran',
                    'action' => 'GetJenisPendaftaran',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_daftar', 'nama_jenis_daftar'],
                ],
                [
                    'name' => 'jalur_masuk',
                    'action' => 'GetJalurMasuk',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jalur_masuk', 'nama_jalur_masuk'],
                ],
                [
                    'name' => 'pembiayaan',
                    'action' => 'GetPembiayaan',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_pembiayaan', 'nama_pembiayaan'],
                ],
                [
                    'name' => 'status_mahasiswa',
                    'action' => 'GetStatusMahasiswa',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_status_mahasiswa', 'nama_status_mahasiswa'],
                ],
                [
                    'name' => 'jenis_keluar',
                    'action' => 'GetJenisKeluar',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_keluar', 'nama_jenis_keluar'],
                ],
                [
                    'name' => 'jenis_evaluasi',
                    'action' => 'GetJenisEvaluasi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_jenis_evaluasi', 'nama_jenis_evaluasi'],
                ],
                [
                    'name' => 'kategori_kegiatan',
                    'action' => 'GetKategoriKegiatan',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_kategori_kegiatan', 'nama_kategori_kegiatan'],
                ],
                [
                    'name' => 'basis_evaluasi',
                    'action' => 'GetBasisEvaluasi',
                    'type' => 'list',
                    'payload_mode' => 'filter',
                    'response_fields' => ['id_basis_evaluasi', 'nama_basis_evaluasi'],
                ],
            ],
        ],
        'mahasiswa_biodata' => [
            'key' => 'mahasiswa_biodata',
            'label' => 'Biodata Mahasiswa',
            'description' => 'Biodata pokok mahasiswa untuk InsertBiodataMahasiswa dan identitas awal sebelum riwayat pendidikan.',
            'sheet_name' => 'mahasiswa_biodata',
            'depends_on' => ['references'],
            'natural_key' => ['nik'],
            'identity_fields' => ['id_mahasiswa'],
            'sort_order' => 100,
            'fields' => [
                ['name' => 'id_mahasiswa', 'label' => 'ID Mahasiswa', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete. Kosong saat insert baru.'],
                ['name' => 'nama_mahasiswa', 'label' => 'Nama Mahasiswa', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 100],
                ['name' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 1, 'rules' => ['enum:L,P,*']],
                ['name' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 32],
                ['name' => 'tanggal_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'nullable' => false, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_agama', 'label' => 'Agama', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetAgama'],
                ['name' => 'nik', 'label' => 'NIK', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 16, 'rules' => ['digits:16']],
                ['name' => 'nisn', 'label' => 'NISN', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 10],
                ['name' => 'npwp', 'label' => 'NPWP', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 15],
                ['name' => 'kewarganegaraan', 'label' => 'Kewarganegaraan', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 2, 'reference' => 'GetNegara'],
                ['name' => 'jalan', 'label' => 'Jalan', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 80],
                ['name' => 'dusun', 'label' => 'Dusun', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 60],
                ['name' => 'rt', 'label' => 'RT', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2],
                ['name' => 'rw', 'label' => 'RW', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2],
                ['name' => 'kelurahan', 'label' => 'Kelurahan', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 60],
                ['name' => 'kode_pos', 'label' => 'Kode Pos', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 5],
                ['name' => 'id_wilayah', 'label' => 'Wilayah', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 8, 'reference' => 'GetWilayah'],
                ['name' => 'id_jenis_tinggal', 'label' => 'Jenis Tinggal', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenisTinggal'],
                ['name' => 'id_alat_transportasi', 'label' => 'Alat Transportasi', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetAlatTransportasi'],
                ['name' => 'telepon', 'label' => 'Telepon', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 20],
                ['name' => 'handphone', 'label' => 'Handphone', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 20],
                ['name' => 'email', 'label' => 'Email', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 60, 'rules' => ['email_warning']],
                ['name' => 'penerima_kps', 'label' => 'Penerima KPS', 'type' => 'boolean01', 'required' => true, 'nullable' => false, 'rules' => ['enum:0,1']],
                ['name' => 'nomor_kps', 'label' => 'Nomor KPS', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 80, 'rules' => ['required_warning_if:penerima_kps,1']],
                ['name' => 'nik_ayah', 'label' => 'NIK Ayah', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 16, 'rules' => ['digits_if_filled:16']],
                ['name' => 'nama_ayah', 'label' => 'Nama Ayah', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 100],
                ['name' => 'tanggal_lahir_ayah', 'label' => 'Tanggal Lahir Ayah', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_pendidikan_ayah', 'label' => 'Pendidikan Ayah', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenjangPendidikan'],
                ['name' => 'id_pekerjaan_ayah', 'label' => 'Pekerjaan Ayah', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPekerjaan'],
                ['name' => 'id_penghasilan_ayah', 'label' => 'Penghasilan Ayah', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPenghasilan'],
                ['name' => 'nik_ibu', 'label' => 'NIK Ibu', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 16, 'rules' => ['digits_if_filled:16']],
                ['name' => 'nama_ibu_kandung', 'label' => 'Nama Ibu Kandung', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 100],
                ['name' => 'tanggal_lahir_ibu', 'label' => 'Tanggal Lahir Ibu', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_pendidikan_ibu', 'label' => 'Pendidikan Ibu', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenjangPendidikan'],
                ['name' => 'id_pekerjaan_ibu', 'label' => 'Pekerjaan Ibu', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPekerjaan'],
                ['name' => 'id_penghasilan_ibu', 'label' => 'Penghasilan Ibu', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPenghasilan'],
                ['name' => 'nama_wali', 'label' => 'Nama Wali', 'type' => 'string', 'required' => false, 'nullable' => true, 'max_length' => 100],
                ['name' => 'tanggal_lahir_wali', 'label' => 'Tanggal Lahir Wali', 'type' => 'date', 'required' => false, 'nullable' => true, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_pendidikan_wali', 'label' => 'Pendidikan Wali', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 2, 'reference' => 'GetJenjangPendidikan'],
                ['name' => 'id_pekerjaan_wali', 'label' => 'Pekerjaan Wali', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPekerjaan'],
                ['name' => 'id_penghasilan_wali', 'label' => 'Penghasilan Wali', 'type' => 'integer', 'required' => false, 'nullable' => true, 'reference' => 'GetPenghasilan'],
                ['name' => 'id_kebutuhan_khusus_mahasiswa', 'label' => 'Kebutuhan Khusus Mahasiswa', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetKebutuhanKhusus', 'example' => 0],
                ['name' => 'id_kebutuhan_khusus_ayah', 'label' => 'Kebutuhan Khusus Ayah', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetKebutuhanKhusus', 'example' => 0],
                ['name' => 'id_kebutuhan_khusus_ibu', 'label' => 'Kebutuhan Khusus Ibu', 'type' => 'integer', 'required' => true, 'nullable' => false, 'reference' => 'GetKebutuhanKhusus', 'example' => 0],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetBiodataMahasiswa', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_mahasiswa']],
                ['name' => 'insert', 'action' => 'InsertBiodataMahasiswa', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_mahasiswa']],
                ['name' => 'update', 'action' => 'UpdateBiodataMahasiswa', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_mahasiswa']],
                ['name' => 'delete', 'action' => 'DeleteBiodataMahasiswa', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_mahasiswa']],
            ],
        ],
        'mahasiswa_riwayat_pendidikan' => [
            'key' => 'mahasiswa_riwayat_pendidikan',
            'label' => 'Riwayat Pendidikan Mahasiswa',
            'description' => 'Registrasi mahasiswa pada program studi/periode masuk setelah biodata mahasiswa tersimpan.',
            'sheet_name' => 'mahasiswa_riwayat_pendidikan',
            'depends_on' => ['references', 'mahasiswa_biodata'],
            'natural_key' => ['nim', 'id_prodi', 'id_periode_masuk'],
            'identity_fields' => ['id_registrasi_mahasiswa'],
            'sort_order' => 110,
            'fields' => [
                ['name' => 'id_registrasi_mahasiswa', 'label' => 'ID Registrasi Mahasiswa', 'type' => 'uuid', 'primary' => true, 'required' => false, 'nullable' => true, 'description' => 'Identity Neo Feeder untuk update/delete riwayat pendidikan. Kosong saat insert baru.'],
                ['name' => 'id_mahasiswa', 'label' => 'ID Mahasiswa', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'mahasiswa_biodata.id_mahasiswa'],
                ['name' => 'nim', 'label' => 'NIM', 'type' => 'string', 'required' => true, 'nullable' => false, 'max_length' => 24],
                ['name' => 'id_jenis_daftar', 'label' => 'Jenis Pendaftaran', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'max_length' => 2, 'reference' => 'GetJenisPendaftaran'],
                ['name' => 'id_jalur_daftar', 'label' => 'Jalur Masuk', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 4, 'reference' => 'GetJalurMasuk'],
                ['name' => 'id_periode_masuk', 'label' => 'Periode Masuk', 'type' => 'char', 'required' => true, 'nullable' => false, 'max_length' => 5, 'reference' => 'GetSemester'],
                ['name' => 'tanggal_daftar', 'label' => 'Tanggal Daftar', 'type' => 'date', 'required' => true, 'nullable' => false, 'format' => 'yyyy-mm-dd'],
                ['name' => 'id_perguruan_tinggi', 'label' => 'Perguruan Tinggi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProfilPT'],
                ['name' => 'id_prodi', 'label' => 'Program Studi', 'type' => 'uuid', 'required' => true, 'nullable' => false, 'reference' => 'GetProdi'],
                ['name' => 'id_bidang_minat', 'label' => 'Bidang Minat', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetListBidangMinat'],
                ['name' => 'sks_diakui', 'label' => 'SKS Diakui', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'max_length' => 3],
                ['name' => 'id_perguruan_tinggi_asal', 'label' => 'Perguruan Tinggi Asal', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetAllPT'],
                ['name' => 'id_prodi_asal', 'label' => 'Program Studi Asal', 'type' => 'uuid', 'required' => false, 'nullable' => true, 'reference' => 'GetAllProdi'],
                ['name' => 'id_pembiayaan', 'label' => 'Pembiayaan', 'type' => 'numeric', 'required' => false, 'nullable' => true, 'reference' => 'GetPembiayaan'],
                ['name' => 'biaya_masuk', 'label' => 'Biaya Masuk', 'type' => 'numeric', 'required' => true, 'nullable' => false, 'rules' => ['decimal:16,2']],
            ],
            'operations' => [
                ['name' => 'get', 'action' => 'GetListRiwayatPendidikanMahasiswa', 'type' => 'list', 'payload_mode' => 'filter', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'insert', 'action' => 'InsertRiwayatPendidikanMahasiswa', 'type' => 'insert', 'payload_mode' => 'record', 'response_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'update', 'action' => 'UpdateRiwayatPendidikanMahasiswa', 'type' => 'update', 'payload_mode' => 'key_record', 'key_fields' => ['id_registrasi_mahasiswa']],
                ['name' => 'delete', 'action' => 'DeleteRiwayatPendidikanMahasiswa', 'type' => 'delete', 'payload_mode' => 'key_only', 'key_fields' => ['id_registrasi_mahasiswa']],
            ],
        ],
    ],
];
